namespace: ansible_community
name: postgresql
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ansible_community.postgresql.git
documentation: null
homepage: null
issues: null
