namespace: ansible_community
name: nagios
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:gundalow-collections/ansible_community.git
documentation: null
homepage: null
issues: null
