namespace: ansible_community
name: zabbix
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible_community.mysql: '>=1.0'
repository: git@github.com:ansible-collection-migration/ansible_community.zabbix.git
documentation: null
homepage: null
issues: null
